version: "3.7"

services:
  flash-cv-frontend:
    image: fellipebrandao/front-1:0.1.1
    container_name: flash-cv-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_BASE_URL_BACK=${NEXT_PUBLIC_BASE_URL_BACK}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - flash-cv-network
    restart: unless-stopped

networks:
  flash-cv-network:
    name: flash-cv-network