version: "3.7"

services:
  flash-cv-frontend:
    image: fellipebrandao/flash-cv-frontend:latest
    container_name: flash-cv-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_BASE_URL_BACK=http://localhost:3001
    networks:
      - flash-cv-network
    restart: unless-stopped

networks:
  flash-cv-network:
    name: flash-cv-network
    external: true